# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movieapi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emovieapi.proto\x12\x08movieapi\"H\n\tMovieData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\x0c\n\x04\x63\x61st\x18\x04 \x03(\t\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x1d\n\x0cMovieRequest\x12\r\n\x05title\x18\x01 \x01(\t\":\n\nMovieReply\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\x0c\n\x04\x63\x61st\x18\x03 \x03(\t2\x84\x01\n\tMovieInfo\x12>\n\x0cGetMovieInfo\x12\x16.movieapi.MovieRequest\x1a\x14.movieapi.MovieReply\"\x00\x12\x37\n\x0cSetMovieInfo\x12\x13.movieapi.MovieData\x1a\x10.movieapi.Status\"\x00\x42\x36Z4github.com/cbeam3902/CloudNativeCourse/lab5/movieapib\x06proto3')



_MOVIEDATA = DESCRIPTOR.message_types_by_name['MovieData']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_MOVIEREQUEST = DESCRIPTOR.message_types_by_name['MovieRequest']
_MOVIEREPLY = DESCRIPTOR.message_types_by_name['MovieReply']
MovieData = _reflection.GeneratedProtocolMessageType('MovieData', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEDATA,
  '__module__' : 'movieapi_pb2'
  # @@protoc_insertion_point(class_scope:movieapi.MovieData)
  })
_sym_db.RegisterMessage(MovieData)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'movieapi_pb2'
  # @@protoc_insertion_point(class_scope:movieapi.Status)
  })
_sym_db.RegisterMessage(Status)

MovieRequest = _reflection.GeneratedProtocolMessageType('MovieRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEREQUEST,
  '__module__' : 'movieapi_pb2'
  # @@protoc_insertion_point(class_scope:movieapi.MovieRequest)
  })
_sym_db.RegisterMessage(MovieRequest)

MovieReply = _reflection.GeneratedProtocolMessageType('MovieReply', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEREPLY,
  '__module__' : 'movieapi_pb2'
  # @@protoc_insertion_point(class_scope:movieapi.MovieReply)
  })
_sym_db.RegisterMessage(MovieReply)

_MOVIEINFO = DESCRIPTOR.services_by_name['MovieInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/cbeam3902/CloudNativeCourse/lab5/movieapi'
  _MOVIEDATA._serialized_start=28
  _MOVIEDATA._serialized_end=100
  _STATUS._serialized_start=102
  _STATUS._serialized_end=124
  _MOVIEREQUEST._serialized_start=126
  _MOVIEREQUEST._serialized_end=155
  _MOVIEREPLY._serialized_start=157
  _MOVIEREPLY._serialized_end=215
  _MOVIEINFO._serialized_start=218
  _MOVIEINFO._serialized_end=350
# @@protoc_insertion_point(module_scope)
