# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movieapi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emovieapi.proto\x12\x08movieapi\"H\n\tMovieData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\x0c\n\x04\x63\x61st\x18\x04 \x03(\t\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x1d\n\x0cMovieRequest\x12\r\n\x05title\x18\x01 \x01(\t\":\n\nMovieReply\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\x0c\n\x04\x63\x61st\x18\x03 \x03(\t2\x84\x01\n\tMovieInfo\x12>\n\x0cGetMovieInfo\x12\x16.movieapi.MovieRequest\x1a\x14.movieapi.MovieReply\"\x00\x12\x37\n\x0cSetMovieInfo\x12\x13.movieapi.MovieData\x1a\x10.movieapi.Status\"\x00\x42\x36Z4github.com/cbeam3902/CloudNativeCourse/lab5/movieapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movieapi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/cbeam3902/CloudNativeCourse/lab5/movieapi'
  _MOVIEDATA._serialized_start=28
  _MOVIEDATA._serialized_end=100
  _STATUS._serialized_start=102
  _STATUS._serialized_end=124
  _MOVIEREQUEST._serialized_start=126
  _MOVIEREQUEST._serialized_end=155
  _MOVIEREPLY._serialized_start=157
  _MOVIEREPLY._serialized_end=215
  _MOVIEINFO._serialized_start=218
  _MOVIEINFO._serialized_end=350
# @@protoc_insertion_point(module_scope)
